# Generated by Django 4.2.20 on 2025-06-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ragehumainenotification',
            name='aerophobie',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ragehumainenotification',
            name='autreraison',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Préciser la raison'),
        ),
        migrations.AddField(
            model_name='ragehumainenotification',
            name='coma',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ragehumainenotification',
            name='date_confirmation_IPCI',
            field=models.DateField(blank=True, null=True, verbose_name='Date de confirmation IPCI'),
        ),
        migrations.AddField(
            model_name='ragehumainenotification',
            name='date_prelevement',
            field=models.DateField(blank=True, null=True, verbose_name='Date de prélèvement'),
        ),
        migrations.AddField(
            model_name='ragehumainenotification',
            name='dateserotherapie',
            field=models.DateField(blank=True, null=True, verbose_name='Date de la sérothérapie antitétanique '),
        ),
        migrations.AddField(
            model_name='ragehumainenotification',
            name='hydrophobie',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ragehumainenotification',
            name='hyper_salivation',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ragehumainenotification',
            name='lieu_deces',
            field=models.CharField(blank=True, choices=[('Hôpital', 'Hôpital'), ('Domicile', 'Domicile'), ('Chez un guérisseur', 'Chez un guérisseur'), ('dans un camp de prière', 'dans un camp de prière'), ('au cours du transfert', 'au cours du transfert'), ('Autre lieu de décès', 'Autre lieu de décès')], max_length=100, null=True, verbose_name='Lieu de décès'),
        ),
        migrations.AddField(
            model_name='ragehumainenotification',
            name='lieu_vaccination',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ragehumainenotification',
            name='nbr_dose_recu',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=10, null=True, verbose_name='Nombre de dose recu'),
        ),
        migrations.AddField(
            model_name='ragehumainenotification',
            name='photophobie',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ragehumainenotification',
            name='prelevement_patient',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ragehumainenotification',
            name='raison_absence_vaccination',
            field=models.CharField(blank=True, choices=[('Ignorance', 'Ignorance'), ('Négligence', 'Négligence'), ('Difficultés financières', 'Difficultés financières'), ('Manque de temps', 'Manque de temps'), ('Refus soutiennpropriétaire', 'Refus soutiennpropriétaire'), ('Centre de vaccination éloigné', 'Centre de vaccination éloigné'), ('Motif Inconnu ', 'Motif Inconnu '), ('Autre', 'Autre')], max_length=30, null=True, verbose_name="Raison d'absence de vaccination"),
        ),
        migrations.AddField(
            model_name='ragehumainenotification',
            name='resultat_virologie',
            field=models.CharField(blank=True, choices=[('Positif', 'Positif'), ('Negatif', 'Négatif'), ('Echantillon inadéquat', 'Echantillon inadéquat'), ('Echantillon non trouvé', 'Echantillon non trouvé')], max_length=100, null=True, verbose_name='Résultat analyse'),
        ),
        migrations.AddField(
            model_name='ragehumainenotification',
            name='serotherapie_antitetanique',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ragehumainenotification',
            name='troubles_respiratoires',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ragehumainenotification',
            name='type_echantillon',
            field=models.CharField(blank=True, choices=[('Salive', 'Salive'), ('Peau', 'Peau')], max_length=30, null=True, verbose_name="Préciser le type d'échantillon"),
        ),
        migrations.AlterField(
            model_name='ragehumainenotification',
            name='resultat_analyse',
            field=models.CharField(blank=True, choices=[('Positif', 'Positif'), ('Negatif', 'Négatif')], max_length=10, null=True, verbose_name='Résultat analyse'),
        ),
    ]
