# Generated by Django 4.2.20 on 2025-04-02 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotvaccin',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Ajouté par', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
