# Generated by Django 4.2.20 on 2025-05-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpatient',
            name='proprietaire_animal',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, default='Non', max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='proprietaire_animal',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, default='Non', max_length=10),
        ),
    ]
