# Generated by Django 4.2.20 on 2025-05-22 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ragehumainenotification',
            name='cel',
        ),
        migrations.AddField(
            model_name='ragehumainenotification',
            name='district_declarant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='district_declarant', to='rage.districtsanitaire'),
        ),
        migrations.AddField(
            model_name='ragehumainenotification',
            name='district_expo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='district_dexposition', to='rage.districtsanitaire'),
        ),
        migrations.AddField(
            model_name='ragehumainenotification',
            name='fonction',
            field=models.CharField(default=0, max_length=20, verbose_name='fonction'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ragehumainenotification',
            name='date_notification',
            field=models.DateField(db_index=True, verbose_name='Date de la notification'),
        ),
        migrations.AlterField(
            model_name='ragehumainenotification',
            name='hopital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rage.servicesanitaire'),
        ),
    ]
