# Generated by Django 4.2.20 on 2025-04-27 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpostexposition',
            name='cou',
        ),
        migrations.RemoveField(
            model_name='historicalpostexposition',
            name='tete',
        ),
        migrations.RemoveField(
            model_name='postexposition',
            name='cou',
        ),
        migrations.RemoveField(
            model_name='postexposition',
            name='tete',
        ),
        migrations.AddField(
            model_name='historicalpostexposition',
            name='preciser_tetecou',
            field=models.CharField(db_index=True, default=0, max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalpostexposition',
            name='tete_cou',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postexposition',
            name='preciser_tetecou',
            field=models.CharField(db_index=True, default=0, max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postexposition',
            name='tete_cou',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='abatu',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='agression',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='attaque_collective',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='attaque_provoquee',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='autre',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='autre_nature_exposition',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='connais_proprio',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='contactanimalpositif',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='contactpatientpositif',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='convocation',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='correctement_vaccine',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='dechires',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='desinfection_plaies',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='disparu',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='domestic',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='errant',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='griffure',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='grossesse',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='immunodepression',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='inconnu',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='lavage_plaies',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='lechage_lesee',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='lechage_saine',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='membre_inferieur',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='membre_superieur',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='morsure',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='mort',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='non_vaccine',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='nonajours',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='observance',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='organes_genitaux_externes',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='prelevement_animal',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='probleme_coagulation',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='professionnel',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='prophylaxie',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='saignement_immediat',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='serum_antitetanique',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='surveillance_veterinaire',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='sutures',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='tronc',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='vaccin_antirabique',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='vacinconnu',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='vetements_dechires',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='vetements_presents',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='abatu',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='agression',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], max_length=10),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='attaque_collective',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], max_length=10),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='attaque_provoquee',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], max_length=10),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='autre',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='autre_nature_exposition',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='connais_proprio',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='contactanimalpositif',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='contactpatientpositif',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='convocation',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='correctement_vaccine',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='dechires',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='desinfection_plaies',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='disparu',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='domestic',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='errant',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='griffure',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='grossesse',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='immunodepression',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='inconnu',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='lavage_plaies',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='lechage_lesee',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='lechage_saine',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='membre_inferieur',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='membre_superieur',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='morsure',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='mort',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='non_vaccine',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='nonajours',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='observance',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='organes_genitaux_externes',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='prelevement_animal',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='probleme_coagulation',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='professionnel',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], max_length=10),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='prophylaxie',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='saignement_immediat',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='serum_antitetanique',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='surveillance_veterinaire',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='sutures',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='tronc',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='vaccin_antirabique',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='vacinconnu',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='vetements_dechires',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='vetements_presents',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
    ]
