# Generated by Django 4.2.20 on 2025-05-08 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whatsappmessagelog',
            options={'ordering': ['-date_sent'], 'verbose_name': 'Log message WhatsApp', 'verbose_name_plural': 'Logs messages WhatsApp'},
        ),
        migrations.RenameField(
            model_name='whatsappmessagelog',
            old_name='date_envoi',
            new_name='date_sent',
        ),
        migrations.RemoveField(
            model_name='whatsappmessagelog',
            name='contenu_message',
        ),
        migrations.RemoveField(
            model_name='whatsappmessagelog',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='whatsappmessagelog',
            name='response',
        ),
        migrations.RemoveField(
            model_name='whatsappmessagelog',
            name='statut',
        ),
        migrations.RemoveField(
            model_name='whatsappmessagelog',
            name='template',
        ),
        migrations.AddField(
            model_name='whatsappmessagelog',
            name='body',
            field=models.TextField(default=0, help_text='Contenu du message'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whatsappmessagelog',
            name='sid',
            field=models.CharField(default=0, help_text='Twilio Message SID', max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whatsappmessagelog',
            name='status',
            field=models.CharField(default=0, help_text='Statut du message (queued, sent, delivered, failed…)', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whatsappmessagelog',
            name='to',
            field=models.CharField(default=0, help_text='Numéro destinataire', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whatsappmessagelog',
            name='vaccination',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_logs', to='rage.vaccination'),
            preserve_default=False,
        ),
    ]
