# Generated by Django 4.2.20 on 2025-05-22 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rage', '0002_remove_ragehumainenotification_cel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpatient',
            name='provenance',
            field=models.CharField(blank=True, choices=[('Urbaine', 'Urbaine'), ('Rurale', 'Rurale')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='provenance',
            field=models.CharField(blank=True, choices=[('Urbaine', 'Urbaine'), ('Rurale', 'Rurale')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ragehumainenotification',
            name='adresse',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='ragehumainenotification',
            name='agent_declarant',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Agent déclarant'),
        ),
        migrations.AlterField(
            model_name='ragehumainenotification',
            name='date_notification',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Date de la notification'),
        ),
        migrations.AlterField(
            model_name='ragehumainenotification',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='ragehumainenotification',
            name='fonction',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='fonction'),
        ),
        migrations.AlterField(
            model_name='ragehumainenotification',
            name='service',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='ragehumainenotification',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone'),
        ),
    ]
