# Generated by Django 4.2.20 on 2025-04-02 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rage', '0002_lotvaccin_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvaccination',
            name='lot',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='rage.lotvaccin'),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rage.lotvaccin'),
        ),
    ]
