# Generated by Django 4.2.20 on 2025-05-20 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rage', '0002_alter_whatsappmessagelog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpatient',
            name='district',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='rage.districtsanitaire'),
        ),
        migrations.AddField(
            model_name='patient',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rage.districtsanitaire'),
        ),
    ]
