# Generated by Django 4.2.20 on 2025-04-27 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rage', '0002_remove_historicalpostexposition_cou_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalpostexposition',
            old_name='inconnu',
            new_name='connu',
        ),
        migrations.RenameField(
            model_name='postexposition',
            old_name='inconnu',
            new_name='connu',
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='nbrlesions',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11-15', '11-15'), ('16-20', '16-20'), ('21 et plus', '21 et plus ')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='nbrlesions',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11-15', '11-15'), ('16-20', '16-20'), ('21 et plus', '21 et plus ')], max_length=300, null=True),
        ),
    ]
