# Generated by Django 4.2.20 on 2025-05-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rage', '0002_alter_historicalpatient_proprietaire_animal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpreexposition',
            name='fin_protocole',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='preexposition',
            name='fin_protocole',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=3, null=True),
        ),
    ]
