# Generated by Django 4.2.20 on 2025-06-17 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rage', '0002_ragehumainenotification_aerophobie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrendezvousvaccination',
            name='rappel_envoye',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rendezvousvaccination',
            name='rappel_envoye',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=30)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('SUCCESS', 'Succès'), ('FAILED', 'Échec')], max_length=10)),
                ('response_content', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('task_id', models.CharField(blank=True, max_length=100, null=True)),
                ('message_length', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Log SMS',
                'verbose_name_plural': 'Logs SMS',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['status', 'sent_at'], name='rage_smslog_status_4f4d10_idx'), models.Index(fields=['phone_number', 'sent_at'], name='rage_smslog_phone_n_5b021f_idx')],
            },
        ),
    ]
