# Generated by Django 4.2.20 on 2025-05-20 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rage', '0003_historicalpatient_district_patient_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='injectionimmunoglobuline',
            name='dose_a_injecter',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Volume injecté en UI ', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='accompagnateur_nature',
            field=models.CharField(blank=True, choices=[('Pere', 'Père'), ('Mere', 'Mère'), ('Oncle', 'Oncle'), ('Tante', 'Tante'), ('Frere', 'Frère'), ('Soeur', 'Soeur'), ('Cousin', 'Cousin'), ('Cousine', 'Cousine'), ('Connaissance du quartier', 'Connaissance du quartier'), ('Voisin du quartier', 'Voisin du quartier'), ('Propriétaire animal', 'Propriétaire animal')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='abatu',
            field=models.CharField(blank=True, choices=[('Carcasse disponible', 'Carcasse disponible'), ('Carcasse non disponible', 'Carcasse non disponible'), ('Non', 'Non')], db_index=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='correctement_vaccine',
            field=models.CharField(blank=True, choices=[('Animal non vacciné', 'Animal non vacciné'), ('Statut vaccinal Inconnu', 'Statut vaccinal Inconnu'), ('Non à jour', 'Non à jour'), ('Oui', 'Correctement vacciné')], db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='mort',
            field=models.CharField(blank=True, choices=[('Carcasse disponible', 'Carcasse disponible'), ('Carcasse non disponible', 'Carcasse non disponible'), ('Non', 'Non')], db_index=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='injectionimmunoglobuline',
            name='dose_ml',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Volume injecté en Unite International', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='accompagnateur_nature',
            field=models.CharField(blank=True, choices=[('Pere', 'Père'), ('Mere', 'Mère'), ('Oncle', 'Oncle'), ('Tante', 'Tante'), ('Frere', 'Frère'), ('Soeur', 'Soeur'), ('Cousin', 'Cousin'), ('Cousine', 'Cousine'), ('Connaissance du quartier', 'Connaissance du quartier'), ('Voisin du quartier', 'Voisin du quartier'), ('Propriétaire animal', 'Propriétaire animal')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='abatu',
            field=models.CharField(blank=True, choices=[('Carcasse disponible', 'Carcasse disponible'), ('Carcasse non disponible', 'Carcasse non disponible'), ('Non', 'Non')], db_index=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='correctement_vaccine',
            field=models.CharField(blank=True, choices=[('Animal non vacciné', 'Animal non vacciné'), ('Statut vaccinal Inconnu', 'Statut vaccinal Inconnu'), ('Non à jour', 'Non à jour'), ('Oui', 'Correctement vacciné')], db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='mort',
            field=models.CharField(blank=True, choices=[('Carcasse disponible', 'Carcasse disponible'), ('Carcasse non disponible', 'Carcasse non disponible'), ('Non', 'Non')], db_index=True, max_length=30, null=True),
        ),
    ]
