# Generated by Django 4.2.20 on 2025-04-27 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rage', '0004_historicalpostexposition_disponible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpostexposition',
            name='autre_statut',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalpostexposition',
            name='autre_statut_precis',
            field=models.CharField(db_index=True, default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postexposition',
            name='autre_statut',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postexposition',
            name='autre_statut_precis',
            field=models.CharField(db_index=True, default=0, max_length=100),
            preserve_default=False,
        ),
    ]
