# Generated by Django 4.2.20 on 2025-04-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rage', '0004_historicalpatient_cni_nni_historicalpatient_cni_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commune',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='contact',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='date_naissance',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='nom',
            field=models.CharField(db_index=True, max_length=225),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='prenoms',
            field=models.CharField(db_index=True, max_length=225),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='date_exposition',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='griffure',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='lieu_exposition',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='morsure',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='historicalpreexposition',
            name='autre',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='historicalpreexposition',
            name='autre_motif',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpreexposition',
            name='chien_voisin',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='historicalpreexposition',
            name='chiens_errants',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='historicalpreexposition',
            name='mise_a_jour',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='historicalpreexposition',
            name='protection_rage',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='historicalpreexposition',
            name='radio',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='historicalpreexposition',
            name='tele',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='historicalpreexposition',
            name='voyage',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='historicalrendezvousvaccination',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalrendezvousvaccination',
            name='date_rendez_vous',
            field=models.DateField(db_index=True, help_text='Date prévue du rendez-vous'),
        ),
        migrations.AlterField(
            model_name='historicalrendezvousvaccination',
            name='dose_numero',
            field=models.IntegerField(db_index=True, help_text='Numéro de la dose dans le protocole'),
        ),
        migrations.AlterField(
            model_name='historicalrendezvousvaccination',
            name='est_effectue',
            field=models.BooleanField(db_index=True, default=False, help_text='Le vaccin a-t-il été administré ?'),
        ),
        migrations.AlterField(
            model_name='historicalrendezvousvaccination',
            name='ordre_rdv',
            field=models.IntegerField(blank=True, db_index=True, help_text='Numéro d’ordre du RDV pour ce patient', null=True),
        ),
        migrations.AlterField(
            model_name='historicalvaccins',
            name='nbr_dose',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='Nombre de dose recquis', null=True),
        ),
        migrations.AlterField(
            model_name='historicalvaccins',
            name='nom',
            field=models.CharField(db_index=True, help_text='Nom du vaccin', max_length=255),
        ),
        migrations.AlterField(
            model_name='lotvaccin',
            name='date_expiration',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='lotvaccin',
            name='date_fabrication',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='code_patient',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=225, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='contact',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_naissance',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mpi_upi',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nom',
            field=models.CharField(db_index=True, max_length=225),
        ),
        migrations.AlterField(
            model_name='patient',
            name='prenoms',
            field=models.CharField(db_index=True, max_length=225),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='date_exposition',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='griffure',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='lieu_exposition',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='morsure',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='preexposition',
            name='autre',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='preexposition',
            name='autre_motif',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='preexposition',
            name='chien_voisin',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='preexposition',
            name='chiens_errants',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='preexposition',
            name='codeexpo',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='preexposition',
            name='mise_a_jour',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='preexposition',
            name='protection_rage',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='preexposition',
            name='radio',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='preexposition',
            name='tele',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='preexposition',
            name='voyage',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='rendezvousvaccination',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='rendezvousvaccination',
            name='date_rendez_vous',
            field=models.DateField(db_index=True, help_text='Date prévue du rendez-vous'),
        ),
        migrations.AlterField(
            model_name='rendezvousvaccination',
            name='dose_numero',
            field=models.IntegerField(db_index=True, help_text='Numéro de la dose dans le protocole'),
        ),
        migrations.AlterField(
            model_name='rendezvousvaccination',
            name='est_effectue',
            field=models.BooleanField(db_index=True, default=False, help_text='Le vaccin a-t-il été administré ?'),
        ),
        migrations.AlterField(
            model_name='rendezvousvaccination',
            name='ordre_rdv',
            field=models.IntegerField(blank=True, db_index=True, help_text='Numéro d’ordre du RDV pour ce patient', null=True),
        ),
        migrations.AlterField(
            model_name='vaccins',
            name='nbr_dose',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='Nombre de dose recquis', null=True),
        ),
        migrations.AlterField(
            model_name='vaccins',
            name='nom',
            field=models.CharField(db_index=True, help_text='Nom du vaccin', max_length=255),
        ),
    ]
