# Generated by Django 4.2.20 on 2025-04-28 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rage', '0005_historicalpostexposition_autre_statut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpostexposition',
            name='carnet_Vaccin',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='postexposition',
            name='carnet_Vaccin',
            field=models.FileField(blank=True, null=True, upload_to='carnets/'),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='retour_info_proprietaire',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='retour_info_proprietaire',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], max_length=50, null=True),
        ),
    ]
