# Generated by Django 4.2.20 on 2025-04-28 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rage', '0006_historicalpostexposition_carnet_vaccin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='preciser_membre_sup',
            field=models.CharField(blank=True, choices=[('epaule', 'Épaule'), ('bras', 'Bras'), ('coude', 'Coude'), ('avant_bras', 'Avant-bras'), ('poignet', 'Poignet'), ('main', 'Main'), ('doigts', 'Doigts')], db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='preciser_membre_sup',
            field=models.CharField(blank=True, choices=[('epaule', 'Épaule'), ('bras', 'Bras'), ('coude', 'Coude'), ('avant_bras', 'Avant-bras'), ('poignet', 'Poignet'), ('main', 'Main'), ('doigts', 'Doigts')], db_index=True, max_length=255, null=True),
        ),
    ]
