# Generated by Django 4.2.20 on 2025-05-20 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rage', '0007_alter_injectionimmunoglobuline_dose_a_injecter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='injectionimmunoglobuline',
            name='dose_a_injecter',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Volume injecté en UI ', max_digits=7, null=True),
        ),
    ]
