# Generated by Django 4.2.20 on 2025-04-28 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rage', '0007_alter_historicalpostexposition_preciser_membre_sup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='preciser_membre_inf',
            field=models.CharField(blank=True, choices=[('Hanche', 'Hanche'), ('Cuisse', 'Cuisse'), ('Genou', 'Genou'), ('Jambe', 'Jambe'), ('Cheville', 'Cheville'), ('Pied', 'Pied'), ('Talon', 'Talon'), ('Plante du pied', 'Plante du pied'), ('Dos du pied', 'Dos du pied'), ('Orteils', 'Orteils')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='preciser_tronc',
            field=models.CharField(blank=True, choices=[('Clavicule', 'Clavicule'), ('Sternum', 'Sternum'), ('Côtes', 'Côtes'), ('Mamelons', 'Mamelons'), ('Seins', 'Seins'), ('Muscles pectoraux', 'Muscles pectoraux'), ('Muscles abdominaux', 'Muscles abdominaux'), ('Nombril', 'Nombril'), ('Flancs', 'Flancs'), ('Muscles obliques', 'Muscles obliques'), ('Omoplates', 'Omoplates'), ('Colonne vertébrale thoracique', 'Colonne vertébrale thoracique'), ('Colonne vertébrale lombaire', 'Colonne vertébrale lombaire'), ('Muscles lombaires', 'Muscles lombaires')], db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='preciser_membre_inf',
            field=models.CharField(blank=True, choices=[('Hanche', 'Hanche'), ('Cuisse', 'Cuisse'), ('Genou', 'Genou'), ('Jambe', 'Jambe'), ('Cheville', 'Cheville'), ('Pied', 'Pied'), ('Talon', 'Talon'), ('Plante du pied', 'Plante du pied'), ('Dos du pied', 'Dos du pied'), ('Orteils', 'Orteils')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='preciser_tronc',
            field=models.CharField(blank=True, choices=[('Clavicule', 'Clavicule'), ('Sternum', 'Sternum'), ('Côtes', 'Côtes'), ('Mamelons', 'Mamelons'), ('Seins', 'Seins'), ('Muscles pectoraux', 'Muscles pectoraux'), ('Muscles abdominaux', 'Muscles abdominaux'), ('Nombril', 'Nombril'), ('Flancs', 'Flancs'), ('Muscles obliques', 'Muscles obliques'), ('Omoplates', 'Omoplates'), ('Colonne vertébrale thoracique', 'Colonne vertébrale thoracique'), ('Colonne vertébrale lombaire', 'Colonne vertébrale lombaire'), ('Muscles lombaires', 'Muscles lombaires')], db_index=True, max_length=255, null=True),
        ),
    ]
