# Generated by Django 4.2.20 on 2025-04-28 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rage', '0008_alter_historicalpostexposition_preciser_membre_inf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpostexposition',
            name='delai_apres_desinfection',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='postexposition',
            name='delai_apres_desinfection',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='antecedents_medicaux',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='antibiotiques',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='details_grosesse',
            field=models.CharField(choices=[('1', 'Semaine 1'), ('2', 'Semaine 2'), ('3', 'Semaine 3'), ('4', 'Semaine 4'), ('5', 'Semaine 5'), ('6', 'Semaine 6'), ('7', 'Semaine 7'), ('8', 'Semaine 8'), ('9', 'Semaine 9'), ('10', 'Semaine 10'), ('11', 'Semaine 11'), ('12', 'Semaine 12'), ('13', 'Semaine 13'), ('14', 'Semaine 14'), ('15', 'Semaine 15'), ('16', 'Semaine 16'), ('17', 'Semaine 17'), ('18', 'Semaine 18'), ('19', 'Semaine 19'), ('20', 'Semaine 20'), ('21', 'Semaine 21'), ('22', 'Semaine 22'), ('23', 'Semaine 23'), ('24', 'Semaine 24'), ('25', 'Semaine 25'), ('26', 'Semaine 26'), ('27', 'Semaine 27'), ('28', 'Semaine 28'), ('29', 'Semaine 29'), ('30', 'Semaine 30'), ('31', 'Semaine 31'), ('32', 'Semaine 32'), ('33', 'Semaine 33'), ('34', 'Semaine 34'), ('35', 'Semaine 35'), ('36', 'Semaine 36'), ('37', 'Semaine 37'), ('38', 'Semaine 38'), ('39', 'Semaine 39'), ('40', 'Semaine 40'), ('41', 'Semaine 41')], db_index=True, default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='preciser_tetecou',
            field=models.CharField(choices=[('Front', 'Front'), ('Yeux', 'Yeux'), ('Nez', 'Nez'), ('Cuire chevelure', 'Cuire chevelure'), ('Bouche', 'Bouche'), ('Oreilles', 'Oreilles'), ('Joues', 'Joues'), ('Menton', 'Menton'), ('Mâchoire', 'Mâchoire'), ('Cou', 'Cou'), ('Nuque', 'Nuque')], db_index=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='preciser_tronc',
            field=models.CharField(blank=True, choices=[('Zone Clavicule', 'Zone Clavicule'), ('Zone Sternum', 'Zone Sternum'), ('Zone Côtes', 'Zone Côtes'), ('Poitrine', 'Poitrine'), ('Seins', 'Seins'), ('Abdomaine', 'Abdomaine'), ('Nombril', 'Nombril'), ('Flancs', 'Flancs'), ('Muscles obliques', 'Muscles obliques'), ('Omoplates', 'Omoplates'), ('Colonne vertébrale thoracique', 'Colonne vertébrale thoracique'), ('Colonne vertébrale lombaire', 'Colonne vertébrale lombaire'), ('Muscles lombaires', 'Muscles lombaires')], db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='antecedents_medicaux',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='antibiotiques',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='details_grosesse',
            field=models.CharField(choices=[('1', 'Semaine 1'), ('2', 'Semaine 2'), ('3', 'Semaine 3'), ('4', 'Semaine 4'), ('5', 'Semaine 5'), ('6', 'Semaine 6'), ('7', 'Semaine 7'), ('8', 'Semaine 8'), ('9', 'Semaine 9'), ('10', 'Semaine 10'), ('11', 'Semaine 11'), ('12', 'Semaine 12'), ('13', 'Semaine 13'), ('14', 'Semaine 14'), ('15', 'Semaine 15'), ('16', 'Semaine 16'), ('17', 'Semaine 17'), ('18', 'Semaine 18'), ('19', 'Semaine 19'), ('20', 'Semaine 20'), ('21', 'Semaine 21'), ('22', 'Semaine 22'), ('23', 'Semaine 23'), ('24', 'Semaine 24'), ('25', 'Semaine 25'), ('26', 'Semaine 26'), ('27', 'Semaine 27'), ('28', 'Semaine 28'), ('29', 'Semaine 29'), ('30', 'Semaine 30'), ('31', 'Semaine 31'), ('32', 'Semaine 32'), ('33', 'Semaine 33'), ('34', 'Semaine 34'), ('35', 'Semaine 35'), ('36', 'Semaine 36'), ('37', 'Semaine 37'), ('38', 'Semaine 38'), ('39', 'Semaine 39'), ('40', 'Semaine 40'), ('41', 'Semaine 41')], db_index=True, default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='preciser_tetecou',
            field=models.CharField(choices=[('Front', 'Front'), ('Yeux', 'Yeux'), ('Nez', 'Nez'), ('Cuire chevelure', 'Cuire chevelure'), ('Bouche', 'Bouche'), ('Oreilles', 'Oreilles'), ('Joues', 'Joues'), ('Menton', 'Menton'), ('Mâchoire', 'Mâchoire'), ('Cou', 'Cou'), ('Nuque', 'Nuque')], db_index=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='preciser_tronc',
            field=models.CharField(blank=True, choices=[('Zone Clavicule', 'Zone Clavicule'), ('Zone Sternum', 'Zone Sternum'), ('Zone Côtes', 'Zone Côtes'), ('Poitrine', 'Poitrine'), ('Seins', 'Seins'), ('Abdomaine', 'Abdomaine'), ('Nombril', 'Nombril'), ('Flancs', 'Flancs'), ('Muscles obliques', 'Muscles obliques'), ('Omoplates', 'Omoplates'), ('Colonne vertébrale thoracique', 'Colonne vertébrale thoracique'), ('Colonne vertébrale lombaire', 'Colonne vertébrale lombaire'), ('Muscles lombaires', 'Muscles lombaires')], db_index=True, max_length=255, null=True),
        ),
    ]
