# Generated by Django 4.2.20 on 2025-05-21 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rage', '0008_alter_injectionimmunoglobuline_dose_a_injecter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='injectionimmunoglobuline',
            old_name='dose_ml',
            new_name='dose_ui',
        ),
        migrations.AlterField(
            model_name='injectionimmunoglobuline',
            name='type_produit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
