# Generated by Django 4.2.20 on 2025-05-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rage', '0009_rename_dose_ml_injectionimmunoglobuline_dose_ui_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpatient',
            name='proprietaire_animal',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, default='Non', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='injectionimmunoglobuline',
            name='dose_a_injecter',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Dose à prescrire en UI ', max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='proprietaire_animal',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, default='Non', max_length=10, null=True),
        ),
    ]
