# Generated by Django 4.2.20 on 2025-04-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rage', '0009_historicalpostexposition_delai_apres_desinfection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='abatu',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='antibiotiques',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='connais_proprio',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='connu',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='convocation',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='correctement_vaccine',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='desinfection_plaies',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='details_grosesse',
            field=models.CharField(blank=True, choices=[('1', 'Semaine 1'), ('2', 'Semaine 2'), ('3', 'Semaine 3'), ('4', 'Semaine 4'), ('5', 'Semaine 5'), ('6', 'Semaine 6'), ('7', 'Semaine 7'), ('8', 'Semaine 8'), ('9', 'Semaine 9'), ('10', 'Semaine 10'), ('11', 'Semaine 11'), ('12', 'Semaine 12'), ('13', 'Semaine 13'), ('14', 'Semaine 14'), ('15', 'Semaine 15'), ('16', 'Semaine 16'), ('17', 'Semaine 17'), ('18', 'Semaine 18'), ('19', 'Semaine 19'), ('20', 'Semaine 20'), ('21', 'Semaine 21'), ('22', 'Semaine 22'), ('23', 'Semaine 23'), ('24', 'Semaine 24'), ('25', 'Semaine 25'), ('26', 'Semaine 26'), ('27', 'Semaine 27'), ('28', 'Semaine 28'), ('29', 'Semaine 29'), ('30', 'Semaine 30'), ('31', 'Semaine 31'), ('32', 'Semaine 32'), ('33', 'Semaine 33'), ('34', 'Semaine 34'), ('35', 'Semaine 35'), ('36', 'Semaine 36'), ('37', 'Semaine 37'), ('38', 'Semaine 38'), ('39', 'Semaine 39'), ('40', 'Semaine 40'), ('41', 'Semaine 41')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='disparu',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='disponible',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='domestic',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='errant',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='grossesse',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='lavage_plaies',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='mort',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='non_vaccine',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='nonajours',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='observance',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='prelevement_animal',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='prophylaxie',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='serum_antitetanique',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='surveillance_veterinaire',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='sutures',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='vaccin_antirabique',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='vacinconnu',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='abatu',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='antibiotiques',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='connais_proprio',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='connu',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='convocation',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='correctement_vaccine',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='desinfection_plaies',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='details_grosesse',
            field=models.CharField(blank=True, choices=[('1', 'Semaine 1'), ('2', 'Semaine 2'), ('3', 'Semaine 3'), ('4', 'Semaine 4'), ('5', 'Semaine 5'), ('6', 'Semaine 6'), ('7', 'Semaine 7'), ('8', 'Semaine 8'), ('9', 'Semaine 9'), ('10', 'Semaine 10'), ('11', 'Semaine 11'), ('12', 'Semaine 12'), ('13', 'Semaine 13'), ('14', 'Semaine 14'), ('15', 'Semaine 15'), ('16', 'Semaine 16'), ('17', 'Semaine 17'), ('18', 'Semaine 18'), ('19', 'Semaine 19'), ('20', 'Semaine 20'), ('21', 'Semaine 21'), ('22', 'Semaine 22'), ('23', 'Semaine 23'), ('24', 'Semaine 24'), ('25', 'Semaine 25'), ('26', 'Semaine 26'), ('27', 'Semaine 27'), ('28', 'Semaine 28'), ('29', 'Semaine 29'), ('30', 'Semaine 30'), ('31', 'Semaine 31'), ('32', 'Semaine 32'), ('33', 'Semaine 33'), ('34', 'Semaine 34'), ('35', 'Semaine 35'), ('36', 'Semaine 36'), ('37', 'Semaine 37'), ('38', 'Semaine 38'), ('39', 'Semaine 39'), ('40', 'Semaine 40'), ('41', 'Semaine 41')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='disparu',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='disponible',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='domestic',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='errant',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='grossesse',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='lavage_plaies',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='mort',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='non_vaccine',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='nonajours',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='observance',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='prelevement_animal',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='prophylaxie',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='serum_antitetanique',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='surveillance_veterinaire',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='sutures',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='vaccin_antirabique',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='vacinconnu',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10, null=True),
        ),
    ]
