# Generated by Django 4.2.20 on 2025-05-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rage', '0010_alter_historicalpatient_proprietaire_animal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpostexposition',
            name='temps_saisie',
            field=models.PositiveIntegerField(blank=True, help_text='Temps de saisie du formulaire (en secondes)', null=True),
        ),
        migrations.AddField(
            model_name='postexposition',
            name='temps_saisie',
            field=models.PositiveIntegerField(blank=True, help_text='Temps de saisie du formulaire (en secondes)', null=True),
        ),
    ]
