# Generated by Django 4.2.20 on 2025-04-28 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rage', '0010_alter_historicalpostexposition_abatu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpostexposition',
            name='preciser_membre_inf',
        ),
        migrations.RemoveField(
            model_name='historicalpostexposition',
            name='preciser_membre_sup',
        ),
        migrations.RemoveField(
            model_name='historicalpostexposition',
            name='preciser_tetecou',
        ),
        migrations.RemoveField(
            model_name='historicalpostexposition',
            name='preciser_tronc',
        ),
        migrations.RemoveField(
            model_name='postexposition',
            name='preciser_membre_inf',
        ),
        migrations.RemoveField(
            model_name='postexposition',
            name='preciser_membre_sup',
        ),
        migrations.RemoveField(
            model_name='postexposition',
            name='preciser_tetecou',
        ),
        migrations.RemoveField(
            model_name='postexposition',
            name='preciser_tronc',
        ),
    ]
