# Generated by Django 4.2.20 on 2025-04-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rage', '0011_remove_historicalpostexposition_preciser_membre_inf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='info_proprietaire',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='info_proprietaire',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], max_length=50, null=True),
        ),
    ]
