# Generated by Django 4.2.20 on 2025-04-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rage', '0012_alter_historicalpostexposition_info_proprietaire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='lechage_saine',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='lechage_saine',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10, null=True),
        ),
    ]
