# Generated by Django 4.2.20 on 2025-04-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rage', '0013_alter_historicalpostexposition_lechage_saine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='autre_nature_exposition',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='autre_nature_exposition',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
    ]
