# Generated by Django 4.2.20 on 2025-04-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rage', '0015_alter_historicalpostexposition_vetements_dechires_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpostexposition',
            name='preciser_membre_sup',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postexposition',
            name='preciser_membre_sup',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='carnet_vaccinal',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='delai_apres_desinfection',
            field=models.CharField(blank=True, choices=[('0', "moin d'une heure"), ('1-2', '1 -2 heure'), ('3-4', '3-4 heure'), ('5-6', '5-6 heure')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='delai_apres_exposition',
            field=models.CharField(blank=True, choices=[('0', "moin d'une heure"), ('1-2', '1 -2 heure'), ('3-4', '3-4 heure'), ('5-6', '5-6 heure')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='carnet_vaccinal',
            field=models.FileField(blank=True, null=True, upload_to='carnets/'),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='delai_apres_desinfection',
            field=models.CharField(blank=True, choices=[('0', "moin d'une heure"), ('1-2', '1 -2 heure'), ('3-4', '3-4 heure'), ('5-6', '5-6 heure')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='delai_apres_exposition',
            field=models.CharField(blank=True, choices=[('0', "moin d'une heure"), ('1-2', '1 -2 heure'), ('3-4', '3-4 heure'), ('5-6', '5-6 heure')], max_length=50, null=True),
        ),
    ]
