# Generated by Django 4.2.20 on 2025-04-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rage', '0016_historicalpostexposition_preciser_membre_sup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpostexposition',
            name='preciser_membre_inf',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpostexposition',
            name='preciser_tetecou',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpostexposition',
            name='preciser_tronc',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postexposition',
            name='preciser_membre_inf',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postexposition',
            name='preciser_tetecou',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postexposition',
            name='preciser_tronc',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
