# Generated by Django 4.2.20 on 2025-04-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rage', '0017_historicalpostexposition_preciser_membre_inf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='autre_statut_precis',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='autre_statut_precis',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
