# Generated by Django 4.2.20 on 2025-04-30 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rage', '0018_alter_historicalpostexposition_autre_statut_precis_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeuser',
            options={'verbose_name': 'Employé', 'verbose_name_plural': 'Employés'},
        ),
        migrations.AlterField(
            model_name='historicalpreexposition',
            name='aime_animaux',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=3),
        ),
        migrations.AlterField(
            model_name='historicalpreexposition',
            name='autre',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, default='Non', max_length=3),
        ),
        migrations.AlterField(
            model_name='historicalpreexposition',
            name='autre_motif',
            field=models.CharField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpreexposition',
            name='chien_voisin',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, default='Non', max_length=3),
        ),
        migrations.AlterField(
            model_name='historicalpreexposition',
            name='chiens_errants',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, default='Non', max_length=3),
        ),
        migrations.AlterField(
            model_name='historicalpreexposition',
            name='connait_protocole_var',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=3),
        ),
        migrations.AlterField(
            model_name='historicalpreexposition',
            name='diff_canal',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=3),
        ),
        migrations.AlterField(
            model_name='historicalpreexposition',
            name='fin_protocole',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=3),
        ),
        migrations.AlterField(
            model_name='historicalpreexposition',
            name='mise_a_jour',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, default='Non', max_length=3),
        ),
        migrations.AlterField(
            model_name='historicalpreexposition',
            name='passage_car',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=3),
        ),
        migrations.AlterField(
            model_name='historicalpreexposition',
            name='presse',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=3),
        ),
        migrations.AlterField(
            model_name='historicalpreexposition',
            name='proche',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=3),
        ),
        migrations.AlterField(
            model_name='historicalpreexposition',
            name='protection_rage',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, default='Non', max_length=3),
        ),
        migrations.AlterField(
            model_name='historicalpreexposition',
            name='radio',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, default='Non', max_length=3),
        ),
        migrations.AlterField(
            model_name='historicalpreexposition',
            name='sensibilisation',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=3),
        ),
        migrations.AlterField(
            model_name='historicalpreexposition',
            name='tele',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, default='Non', max_length=3),
        ),
        migrations.AlterField(
            model_name='historicalpreexposition',
            name='voyage',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, default='Non', max_length=3),
        ),
        migrations.AlterField(
            model_name='preexposition',
            name='aime_animaux',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=3),
        ),
        migrations.AlterField(
            model_name='preexposition',
            name='autre',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, default='Non', max_length=3),
        ),
        migrations.AlterField(
            model_name='preexposition',
            name='autre_motif',
            field=models.CharField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='preexposition',
            name='chien_voisin',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, default='Non', max_length=3),
        ),
        migrations.AlterField(
            model_name='preexposition',
            name='chiens_errants',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, default='Non', max_length=3),
        ),
        migrations.AlterField(
            model_name='preexposition',
            name='connait_protocole_var',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=3),
        ),
        migrations.AlterField(
            model_name='preexposition',
            name='diff_canal',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=3),
        ),
        migrations.AlterField(
            model_name='preexposition',
            name='fin_protocole',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=3),
        ),
        migrations.AlterField(
            model_name='preexposition',
            name='mise_a_jour',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, default='Non', max_length=3),
        ),
        migrations.AlterField(
            model_name='preexposition',
            name='passage_car',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=3),
        ),
        migrations.AlterField(
            model_name='preexposition',
            name='presse',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=3),
        ),
        migrations.AlterField(
            model_name='preexposition',
            name='proche',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=3),
        ),
        migrations.AlterField(
            model_name='preexposition',
            name='protection_rage',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, default='Non', max_length=3),
        ),
        migrations.AlterField(
            model_name='preexposition',
            name='radio',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, default='Non', max_length=3),
        ),
        migrations.AlterField(
            model_name='preexposition',
            name='sensibilisation',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=3),
        ),
        migrations.AlterField(
            model_name='preexposition',
            name='tele',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, default='Non', max_length=3),
        ),
        migrations.AlterField(
            model_name='preexposition',
            name='voyage',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, default='Non', max_length=3),
        ),
    ]
