# Generated by Django 4.2.20 on 2025-05-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rage', '0019_alter_employeeuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpostexposition',
            name='details_allergies',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpostexposition',
            name='details_antecedents',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpostexposition',
            name='details_traitements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postexposition',
            name='details_allergies',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postexposition',
            name='details_antecedents',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postexposition',
            name='details_traitements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='abatu',
            field=models.CharField(blank=True, choices=[('Caracasse disponible', 'Caracasse disponible'), ('Caracasse non disponible', 'Caracasse non disponible'), ('Non', 'Non')], db_index=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='allergies',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='circonstance',
            field=models.CharField(blank=True, choices=[('Attaque provoquée', 'Attaque provoquée'), ('Agression', 'Agression')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='details_immo',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='details_problemes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='mort',
            field=models.CharField(blank=True, choices=[('Caracasse disponible', 'Caracasse disponible'), ('Caracasse non disponible', 'Caracasse non disponible'), ('Non', 'Non')], db_index=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='traitements_en_cours',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='abatu',
            field=models.CharField(blank=True, choices=[('Caracasse disponible', 'Caracasse disponible'), ('Caracasse non disponible', 'Caracasse non disponible'), ('Non', 'Non')], db_index=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='allergies',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='circonstance',
            field=models.CharField(blank=True, choices=[('Attaque provoquée', 'Attaque provoquée'), ('Agression', 'Agression')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='details_immo',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='details_problemes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='mort',
            field=models.CharField(blank=True, choices=[('Caracasse disponible', 'Caracasse disponible'), ('Caracasse non disponible', 'Caracasse non disponible'), ('Non', 'Non')], db_index=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='traitements_en_cours',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, default=0, max_length=10),
            preserve_default=False,
        ),
    ]
