# Generated by Django 4.2.20 on 2025-05-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rage', '0020_historicalpostexposition_details_allergies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='details_antecedents',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='details_antecedents',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
