# Generated by Django 4.2.20 on 2025-05-01 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rage', '0022_alter_historicalpostexposition_details_antecedents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpostexposition',
            name='carnet_vaccinal_verso',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='postexposition',
            name='carnet_vaccinal_verso',
            field=models.FileField(blank=True, null=True, upload_to='carnets/'),
        ),
    ]
