# Generated by Django 4.2.20 on 2025-05-02 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rage', '0023_historicalpostexposition_carnet_vaccinal_verso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InjectionImmunoglobuline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_injection', models.DateTimeField(default=django.utils.timezone.now)),
                ('type_produit', models.CharField(help_text='Ex: Immunoglobuline antirabique humaine', max_length=100)),
                ('dose_ml', models.DecimalField(decimal_places=2, help_text='Volume injecté en ml', max_digits=5)),
                ('voie_injection', models.CharField(choices=[('IM', 'Intramusculaire'), ('ID', 'Intradermique'), ('SC', 'Sous-cutanée')], max_length=10)),
                ('site_injection', models.TextField(blank=True, help_text="Sites anatomiques d'injection (ex: bras gauche, cuisse droite...)")),
                ('numero_lot', models.CharField(blank=True, max_length=100, null=True)),
                ('date_peremption', models.DateField(blank=True, null=True)),
                ('laboratoire_fabricant', models.CharField(blank=True, max_length=100, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients_immuno', to='rage.patient')),
            ],
            options={
                'verbose_name': "Injection d'immunoglobuline",
                'verbose_name_plural': "Injections d'immunoglobuline",
                'ordering': ['-date_injection'],
            },
        ),
    ]
