# Generated by Django 4.2.20 on 2025-05-02 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rage', '0025_alter_historicalpostexposition_attaque_provoquee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='agression',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='agression',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], max_length=10, null=True),
        ),
    ]
