# Generated by Django 4.2.20 on 2025-05-02 20:25

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('rage', '0026_alter_historicalpostexposition_agression_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpatient',
            name='accompagnateur_contact',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='CI'),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, max_length=128, null=True, region='CI'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='accompagnateur_contact',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='CI'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, max_length=128, null=True, region='CI'),
        ),
    ]
