# Generated by Django 4.2.20 on 2025-05-02 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rage', '0027_alter_historicalpatient_accompagnateur_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postexposition',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patientpep', to='rage.patient'),
        ),
    ]
