# Generated by Django 4.2.20 on 2025-05-03 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rage', '0028_alter_postexposition_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='injectionimmunoglobuline',
            options={'ordering': ['-date_injection']},
        ),
        migrations.AddField(
            model_name='injectionimmunoglobuline',
            name='motif_refus',
            field=models.TextField(blank=True, help_text='Motif du refus (si refusé)', null=True),
        ),
        migrations.AddField(
            model_name='injectionimmunoglobuline',
            name='refus_injection',
            field=models.BooleanField(default=False, help_text="Le patient a-t-il refusé l'injection ?"),
        ),
        migrations.AlterField(
            model_name='injectionimmunoglobuline',
            name='dose_ml',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Volume injecté en ml', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='injectionimmunoglobuline',
            name='site_injection',
            field=models.TextField(blank=True, help_text="Sites anatomiques d'injection (ex: bras gauche, cuisse droite...)", null=True),
        ),
        migrations.AlterField(
            model_name='injectionimmunoglobuline',
            name='type_produit',
            field=models.CharField(blank=True, help_text='Ex: Immunoglobuline antirabique humaine', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='injectionimmunoglobuline',
            name='voie_injection',
            field=models.CharField(blank=True, choices=[('IM', 'Intramusculaire'), ('ID', 'Intradermique'), ('SC', 'Sous-cutanée')], max_length=10, null=True),
        ),
    ]
