# Generated by Django 4.2.20 on 2025-05-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rage', '0029_alter_injectionimmunoglobuline_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpatient',
            name='poids',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='poids',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
