# Generated by Django 4.2.20 on 2025-05-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rage', '0030_historicalpatient_poids_patient_poids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpatient',
            name='poids',
            field=models.PositiveIntegerField(blank=True, help_text='Poids du patient en kilogrammes', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='poids',
            field=models.PositiveIntegerField(blank=True, help_text='Poids du patient en kilogrammes', null=True),
        ),
    ]
