# Generated by Django 4.2.20 on 2025-05-03 09:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rage', '0031_alter_historicalpatient_poids_alter_patient_poids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpatient',
            name='poids',
            field=models.PositiveIntegerField(blank=True, help_text='Poids du patient (1 à 250 kg)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(250)]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='poids',
            field=models.PositiveIntegerField(blank=True, help_text='Poids du patient (1 à 250 kg)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(250)]),
        ),
    ]
