# Generated by Django 4.2.20 on 2025-05-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rage', '0032_alter_historicalpatient_poids_alter_patient_poids'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppMessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('template', models.CharField(blank=True, max_length=100, null=True)),
                ('contenu_message', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(max_length=20)),
                ('response', models.TextField(blank=True, null=True)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='accompagnateur_nature',
            field=models.CharField(blank=True, choices=[('Pere', 'Pere'), ('Mere', 'Mere'), ('Oncle', 'Oncle'), ('Tante', 'Tante'), ('Frère', 'Frère'), ('Soeure', 'Soeure'), ('Cousin', 'Cousin'), ('Cousine', 'Cousine'), ('Connaissance du quartier', 'Connaissance du quartier'), ('Voisin du quartier', 'Voisin du quartier'), ('Propriétaire animal', 'Propriétaire animal')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='circonstance',
            field=models.CharField(blank=True, choices=[('Attaque provoquée', 'Attaque provoquée'), ('Agression', 'Agression'), ('Contact patient suspect/positif de rage ', 'Contact patient suspect/positif de rage')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='correctement_vaccine',
            field=models.CharField(blank=True, choices=[('Animal non vacciné', 'Animal non vacciné'), ('Statut vaccinal Inconnu', 'Statut vaccinal Inconnu'), ('Non à jour', 'Non à jour'), ('Oui', 'Correctement vaccine')], db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='accompagnateur_nature',
            field=models.CharField(blank=True, choices=[('Pere', 'Pere'), ('Mere', 'Mere'), ('Oncle', 'Oncle'), ('Tante', 'Tante'), ('Frère', 'Frère'), ('Soeure', 'Soeure'), ('Cousin', 'Cousin'), ('Cousine', 'Cousine'), ('Connaissance du quartier', 'Connaissance du quartier'), ('Voisin du quartier', 'Voisin du quartier'), ('Propriétaire animal', 'Propriétaire animal')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='circonstance',
            field=models.CharField(blank=True, choices=[('Attaque provoquée', 'Attaque provoquée'), ('Agression', 'Agression'), ('Contact patient suspect/positif de rage ', 'Contact patient suspect/positif de rage')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='correctement_vaccine',
            field=models.CharField(blank=True, choices=[('Animal non vacciné', 'Animal non vacciné'), ('Statut vaccinal Inconnu', 'Statut vaccinal Inconnu'), ('Non à jour', 'Non à jour'), ('Oui', 'Correctement vaccine')], db_index=True, max_length=50, null=True),
        ),
    ]
