# Generated by Django 4.2.20 on 2025-05-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rage', '0033_whatsappmessagelog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpostexposition',
            name='dechires',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='postexposition',
            name='dechires',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], db_index=True, max_length=10, null=True),
        ),
    ]
