# Generated by Django 4.2.20 on 2025-05-05 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rage', '0034_alter_historicalpostexposition_dechires_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ragehumainenotification',
            name='district_sanitaire_exposition',
        ),
        migrations.RemoveField(
            model_name='ragehumainenotification',
            name='exposition_commune',
        ),
        migrations.AddField(
            model_name='ragehumainenotification',
            name='autre_nature_exposition',
            field=models.CharField(default=0, max_length=120, verbose_name='Autres nature'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ragehumainenotification',
            name='exposition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rage.postexposition'),
        ),
        migrations.AlterField(
            model_name='ragehumainenotification',
            name='agitation',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ragehumainenotification',
            name='desinfection',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ragehumainenotification',
            name='hospitalisation',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ragehumainenotification',
            name='labo_pathologie_animale',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ragehumainenotification',
            name='lieu_exposition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rage.commune'),
        ),
        migrations.AlterField(
            model_name='ragehumainenotification',
            name='prelevement_animal',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ragehumainenotification',
            name='soins_locaux',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ragehumainenotification',
            name='trouble_comportement',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ragehumainenotification',
            name='vaccination_antirabique',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], max_length=10),
        ),
    ]
