# Generated by Django 4.2.20 on 2025-05-05 16:19

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rage', '0035_remove_ragehumainenotification_district_sanitaire_exposition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeServiceSanitaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=500, null=True)),
                ('acronyme', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ragehumainenotification',
            name='lieu_hospitalisation',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ServiceSanitaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('upstream', models.CharField(blank=True, max_length=255, null=True)),
                ('date_modified', models.DateTimeField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True, max_length=500, null=True)),
                ('completeness', models.CharField(blank=True, max_length=100, null=True)),
                ('uuid', models.UUIDField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('what3words', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rage.districtsanitaire')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rage.typeservicesanitaire')),
            ],
        ),
    ]
