# Generated by Django 4.2.20 on 2025-05-07 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rage', '0036_typeservicesanitaire_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpatient',
            name='accompagnateur_contact',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='accompagnateur_contact',
        ),
    ]
