
services:

  rageweb:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 1524:8000  # port du server : port de l'application
    volumes:
      - .:/rage-app/
    env_file:
      - ./.env
    restart: always
    depends_on:
      - rageDB

  rageDB:
    image: postgis/postgis:16-3.4
    platform: linux/amd64
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    networks:
      - rage_default

  adminer:
    image: adminer
    restart: always
    ports:
      - 2502:8080
    networks:
      - rage_default

networks:
  rage_default:
    external: true

volumes:
  pgdata:
    driver: local
  static_volume:
  media_volume: